import Header from "@/components/partials/Header";
import "../globals.css";
import NextTopLoader from "nextjs-toploader";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { NextIntlClientProvider, useLocale, useMessages } from "next-intl";
import Providers from "../providers";
import Footer from "@/components/partials/Footer";
import { Toaster } from "react-hot-toast";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "AniVerse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = useLocale();
  const messages = useMessages();

  return (
    <html lang={locale}>
      <NextIntlClientProvider locale={locale} messages={messages}>
        <Providers>
          <body className={outfit.className}>
            <NextTopLoader color="#EF4444" />
            <Header />
            <main>{children}</main>
            <Footer />
            <Toaster />
          </body>
        </Providers>
      </NextIntlClientProvider>
    </html>
  );
}
